[workspace]
members = [
    "compiler",
    "qt5qml",
    "tests/properties",
    "tests/signals",
    "tests/listmodel",
    "tests/slots",
    "examples/qobject",
    "examples/listmodel"
]

#[profile.bench]
#lto = true